name: workflow pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: release
        required: true
        type: choice
        options:
          - 'dev'
          - 'devint'
        default: 'devint'
      Branch:
        description: Branch Name
        required: true
        default: 'master'
      component:
        type: choice
        description: component
        options:
          - first
          - second
          - all
        default: all
jobs:
  matrix_prep:
    runs-on: [self-hosted]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Matrix
        id: set-matrix
        env: 
          component: "${{ github.event.inputs.component || 'all' }}"
        run: |
          echo "matrix=$(jq '[.[] | select(.runOn == "${{ env.component }}" or .cdkDeploy == "${{ env.component }}") | .cdkDeploy]' -c .github/workflows/list.json)" >> $GITHUB_OUTPUT
